INSERT OR IGNORE INTO skills (name, slug) VALUES
  ('.NET', 'dotnet'),
  ('Ansible', 'ansible'),
  ('Apache Airflow', 'apache-airflow'),
  ('Apache Kafka', 'apache-kafka'),
  ('Apache Spark', 'apache-spark'),
  ('Angular', 'angular'),
  ('Android', 'android'),
  ('Argo CD', 'argo-cd'),
  ('ASP.NET Core', 'asp-net-core'),
  ('Astro', 'astro'),
  ('AWS', 'aws'),
  ('Azure', 'azure'),
  ('Bash', 'bash'),
  ('BigQuery', 'bigquery'),
  ('C', 'c'),
  ('C#', 'c-sharp'),
  ('C++', 'cpp'),
  ('Cassandra', 'cassandra'),
  ('CircleCI', 'circleci'),
  ('Cloudflare', 'cloudflare'),
  ('Computer Vision', 'computer-vision'),
  ('CSS', 'css'),
  ('Cypress', 'cypress'),
  ('Dart', 'dart'),
  ('Databricks', 'databricks'),
  ('dbt', 'dbt'),
  ('Django', 'django'),
  ('Docker', 'docker'),
  ('DynamoDB', 'dynamodb'),
  ('Elasticsearch', 'elasticsearch'),
  ('Electron', 'electron'),
  ('Elixir', 'elixir'),
  ('Express.js', 'express-js'),
  ('FastAPI', 'fastapi'),
  ('Firebase', 'firebase'),
  ('Flask', 'flask'),
  ('Flutter', 'flutter'),
  ('Git', 'git'),
  ('GitHub Actions', 'github-actions'),
  ('GitLab CI/CD', 'gitlab-ci-cd'),
  ('Go', 'go'),
  ('Google Cloud', 'google-cloud'),
  ('Grafana', 'grafana'),
  ('GraphQL', 'graphql'),
  ('gRPC', 'grpc'),
  ('Helm', 'helm'),
  ('HTML', 'html'),
  ('Hugging Face', 'hugging-face'),
  ('Ionic', 'ionic'),
  ('iOS', 'ios'),
  ('Java', 'java'),
  ('JavaScript', 'javascript'),
  ('Jenkins', 'jenkins'),
  ('Jest', 'jest'),
  ('Jetpack Compose', 'jetpack-compose'),
  ('JUnit', 'junit'),
  ('Jupyter', 'jupyter'),
  ('JWT', 'jwt'),
  ('Keras', 'keras'),
  ('Kotlin', 'kotlin'),
  ('Kubernetes', 'kubernetes'),
  ('LangChain', 'langchain'),
  ('Laravel', 'laravel'),
  ('Large Language Models', 'large-language-models'),
  ('Linux', 'linux'),
  ('Lua', 'lua'),
  ('MariaDB', 'mariadb'),
  ('MLOps', 'mlops'),
  ('MongoDB', 'mongodb'),
  ('MySQL', 'mysql'),
  ('Natural Language Processing', 'natural-language-processing'),
  ('NestJS', 'nestjs'),
  ('Next.js', 'next-js'),
  ('Nginx', 'nginx'),
  ('Neo4j', 'neo4j'),
  ('Node.js', 'node-js'),
  ('Nuxt', 'nuxt'),
  ('NumPy', 'numpy'),
  ('OAuth 2.0', 'oauth-2'),
  ('OpenID Connect', 'openid-connect'),
  ('OpenSearch', 'opensearch'),
  ('OpenTelemetry', 'opentelemetry'),
  ('Oracle Database', 'oracle-database'),
  ('OWASP', 'owasp'),
  ('Pandas', 'pandas'),
  ('Penetration Testing', 'penetration-testing'),
  ('PHP', 'php'),
  ('Phoenix', 'phoenix'),
  ('Playwright', 'playwright'),
  ('PostgreSQL', 'postgresql'),
  ('Postman', 'postman'),
  ('Prometheus', 'prometheus'),
  ('Pulumi', 'pulumi'),
  ('pytest', 'pytest'),
  ('Python', 'python'),
  ('PyTorch', 'pytorch'),
  ('R', 'r'),
  ('RabbitMQ', 'rabbitmq'),
  ('React', 'react'),
  ('React Native', 'react-native'),
  ('React Testing Library', 'react-testing-library'),
  ('Redis', 'redis'),
  ('Redux', 'redux'),
  ('Remix', 'remix'),
  ('REST APIs', 'rest-apis'),
  ('Retrieval-Augmented Generation', 'retrieval-augmented-generation'),
  ('Ruby', 'ruby'),
  ('Ruby on Rails', 'ruby-on-rails'),
  ('Rust', 'rust'),
  ('SAST', 'sast'),
  ('Scala', 'scala'),
  ('scikit-learn', 'scikit-learn'),
  ('Selenium', 'selenium'),
  ('Serverless', 'serverless'),
  ('Snowflake', 'snowflake'),
  ('Solidity', 'solidity'),
  ('Spring Boot', 'spring-boot'),
  ('SQL Server', 'sql-server'),
  ('SQLite', 'sqlite'),
  ('Storybook', 'storybook'),
  ('Supabase', 'supabase'),
  ('Svelte', 'svelte'),
  ('SvelteKit', 'sveltekit'),
  ('Swift', 'swift'),
  ('SwiftUI', 'swiftui'),
  ('Symfony', 'symfony'),
  ('Tailwind CSS', 'tailwind-css'),
  ('TensorFlow', 'tensorflow'),
  ('Terraform', 'terraform'),
  ('TypeScript', 'typescript'),
  ('Unity', 'unity'),
  ('Vite', 'vite'),
  ('Vitest', 'vitest'),
  ('Vue.js', 'vue-js'),
  ('Web Components', 'web-components');
