-- Curated against SFIA 9, ESCO/e-CF, NIST NICE, and O*NET IT skill domains.
-- Categories are comments only; the existing schema intentionally stores canonical skills.
INSERT OR IGNORE INTO skills (name, slug) VALUES
  -- Programming languages (31)
  ('.NET', 'dotnet'),
  ('Assembly', 'assembly'),
  ('Bash', 'bash'),
  ('C', 'c'),
  ('C#', 'c-sharp'),
  ('C++', 'cpp'),
  ('Clojure', 'clojure'),
  ('COBOL', 'cobol'),
  ('Dart', 'dart'),
  ('Elixir', 'elixir'),
  ('Elm', 'elm'),
  ('Erlang', 'erlang'),
  ('F#', 'f-sharp'),
  ('Fortran', 'fortran'),
  ('Go', 'go'),
  ('Groovy', 'groovy'),
  ('Haskell', 'haskell'),
  ('Java', 'java'),
  ('JavaScript', 'javascript'),
  ('Julia', 'julia'),
  ('Kotlin', 'kotlin'),
  ('Lua', 'lua'),
  ('MATLAB', 'matlab'),
  ('Objective-C', 'objective-c'),
  ('PHP', 'php'),
  ('Python', 'python'),
  ('R', 'r'),
  ('Ruby', 'ruby'),
  ('Rust', 'rust'),
  ('Scala', 'scala'),
  ('TypeScript', 'typescript'),

  -- Frontend and web (30)
  ('Angular', 'angular'),
  ('Astro', 'astro'),
  ('Bootstrap', 'bootstrap'),
  ('CSS', 'css'),
  ('D3.js', 'd3-js'),
  ('Electron', 'electron'),
  ('Ember.js', 'ember-js'),
  ('Gatsby', 'gatsby'),
  ('HTML', 'html'),
  ('HTMX', 'htmx'),
  ('jQuery', 'jquery'),
  ('Lit', 'lit'),
  ('Material UI', 'material-ui'),
  ('Next.js', 'next-js'),
  ('Nuxt', 'nuxt'),
  ('Progressive Web Apps', 'progressive-web-apps'),
  ('React', 'react'),
  ('Redux', 'redux'),
  ('Remix', 'remix'),
  ('Responsive Web Design', 'responsive-web-design'),
  ('Sass', 'sass'),
  ('SolidJS', 'solidjs'),
  ('Storybook', 'storybook'),
  ('Svelte', 'svelte'),
  ('SvelteKit', 'sveltekit'),
  ('Tailwind CSS', 'tailwind-css'),
  ('Vite', 'vite'),
  ('Vue.js', 'vue-js'),
  ('Web Accessibility', 'web-accessibility'),
  ('Web Components', 'web-components'),

  -- Backend and APIs (30)
  ('API Design', 'api-design'),
  ('ASP.NET Core', 'asp-net-core'),
  ('Deno', 'deno'),
  ('Django', 'django'),
  ('Dropwizard', 'dropwizard'),
  ('Express.js', 'express-js'),
  ('FastAPI', 'fastapi'),
  ('Flask', 'flask'),
  ('GraphQL', 'graphql'),
  ('gRPC', 'grpc'),
  ('Jakarta EE', 'jakarta-ee'),
  ('Laravel', 'laravel'),
  ('Micronaut', 'micronaut'),
  ('Microservices', 'microservices'),
  ('NestJS', 'nestjs'),
  ('Node.js', 'node-js'),
  ('OpenAPI', 'openapi'),
  ('Phoenix', 'phoenix'),
  ('Quarkus', 'quarkus'),
  ('RabbitMQ', 'rabbitmq'),
  ('REST APIs', 'rest-apis'),
  ('Ruby on Rails', 'ruby-on-rails'),
  ('Server-Sent Events', 'server-sent-events'),
  ('SOAP', 'soap'),
  ('Spring Boot', 'spring-boot'),
  ('Symfony', 'symfony'),
  ('WebSockets', 'websockets'),
  ('Webhooks', 'webhooks'),
  ('WebRTC', 'webrtc'),
  ('ZeroMQ', 'zeromq'),

  -- Mobile (18)
  ('Android', 'android'),
  ('Android SDK', 'android-sdk'),
  ('Capacitor', 'capacitor'),
  ('Expo', 'expo'),
  ('Firebase', 'firebase'),
  ('Flutter', 'flutter'),
  ('Ionic', 'ionic'),
  ('iOS', 'ios'),
  ('Jetpack Compose', 'jetpack-compose'),
  ('Kotlin Multiplatform', 'kotlin-multiplatform'),
  ('.NET MAUI', 'dotnet-maui'),
  ('Mobile Accessibility', 'mobile-accessibility'),
  ('Mobile App Security', 'mobile-app-security'),
  ('React Native', 'react-native'),
  ('Swift', 'swift'),
  ('SwiftUI', 'swiftui'),
  ('UIKit', 'uikit'),
  ('Xamarin', 'xamarin'),

  -- Databases and data stores (27)
  ('Amazon Aurora', 'amazon-aurora'),
  ('Amazon RDS', 'amazon-rds'),
  ('Cassandra', 'cassandra'),
  ('CockroachDB', 'cockroachdb'),
  ('Couchbase', 'couchbase'),
  ('CouchDB', 'couchdb'),
  ('Database Administration', 'database-administration'),
  ('Database Design', 'database-design'),
  ('DynamoDB', 'dynamodb'),
  ('Elasticsearch', 'elasticsearch'),
  ('Firestore', 'firestore'),
  ('InfluxDB', 'influxdb'),
  ('MariaDB', 'mariadb'),
  ('MongoDB', 'mongodb'),
  ('MySQL', 'mysql'),
  ('Neo4j', 'neo4j'),
  ('OpenSearch', 'opensearch'),
  ('Oracle Database', 'oracle-database'),
  ('PostgreSQL', 'postgresql'),
  ('Redis', 'redis'),
  ('SQL', 'sql'),
  ('SQL Server', 'sql-server'),
  ('SQLite', 'sqlite'),
  ('Supabase', 'supabase'),
  ('TiDB', 'tidb'),
  ('Vector Databases', 'vector-databases'),
  ('Vertica', 'vertica'),

  -- Cloud computing (27)
  ('Alibaba Cloud', 'alibaba-cloud'),
  ('AWS', 'aws'),
  ('AWS CloudFormation', 'aws-cloudformation'),
  ('AWS Lambda', 'aws-lambda'),
  ('Azure', 'azure'),
  ('Azure Functions', 'azure-functions'),
  ('Cloud Architecture', 'cloud-architecture'),
  ('Cloud Cost Management', 'cloud-cost-management'),
  ('Cloud Migration', 'cloud-migration'),
  ('Cloud Security', 'cloud-security'),
  ('Cloudflare', 'cloudflare'),
  ('Cloudflare D1', 'cloudflare-d1'),
  ('Cloudflare Workers', 'cloudflare-workers'),
  ('DigitalOcean', 'digitalocean'),
  ('Edge Computing', 'edge-computing'),
  ('Google Cloud', 'google-cloud'),
  ('Google Cloud Functions', 'google-cloud-functions'),
  ('Heroku', 'heroku'),
  ('Hybrid Cloud', 'hybrid-cloud'),
  ('IBM Cloud', 'ibm-cloud'),
  ('Infrastructure as a Service', 'infrastructure-as-a-service'),
  ('Oracle Cloud', 'oracle-cloud'),
  ('Platform as a Service', 'platform-as-a-service'),
  ('Serverless', 'serverless'),
  ('Software as a Service', 'software-as-a-service'),
  ('Vercel', 'vercel'),
  ('VMware Cloud', 'vmware-cloud'),

  -- DevOps, SRE, and platform engineering (33)
  ('Ansible', 'ansible'),
  ('Argo CD', 'argo-cd'),
  ('Azure DevOps', 'azure-devops'),
  ('Buildkite', 'buildkite'),
  ('CI/CD', 'ci-cd'),
  ('CircleCI', 'circleci'),
  ('Configuration Management', 'configuration-management'),
  ('Consul', 'consul'),
  ('Continuous Delivery', 'continuous-delivery'),
  ('DevOps', 'devops'),
  ('Docker', 'docker'),
  ('Flux CD', 'flux-cd'),
  ('Git', 'git'),
  ('GitHub Actions', 'github-actions'),
  ('GitLab CI/CD', 'gitlab-ci-cd'),
  ('GitOps', 'gitops'),
  ('Gradle', 'gradle'),
  ('Helm', 'helm'),
  ('Infrastructure as Code', 'infrastructure-as-code'),
  ('Jenkins', 'jenkins'),
  ('Kubernetes', 'kubernetes'),
  ('Maven', 'maven'),
  ('Nomad', 'nomad'),
  ('OpenShift', 'openshift'),
  ('Packer', 'packer'),
  ('Platform Engineering', 'platform-engineering'),
  ('Pulumi', 'pulumi'),
  ('Release Management', 'release-management'),
  ('Site Reliability Engineering', 'site-reliability-engineering'),
  ('Sonatype Nexus Repository', 'sonatype-nexus-repository'),
  ('Terraform', 'terraform'),
  ('Vault', 'vault'),
  ('VMware vSphere', 'vmware-vsphere'),

  -- Cybersecurity (32)
  ('Application Security', 'application-security'),
  ('Cloud Security Posture Management', 'cloud-security-posture-management'),
  ('Cryptography', 'cryptography'),
  ('DAST', 'dast'),
  ('Data Loss Prevention', 'data-loss-prevention'),
  ('DevSecOps', 'devsecops'),
  ('Digital Forensics', 'digital-forensics'),
  ('Endpoint Detection and Response', 'endpoint-detection-and-response'),
  ('Ethical Hacking', 'ethical-hacking'),
  ('Governance, Risk, and Compliance', 'governance-risk-compliance'),
  ('Identity and Access Management', 'identity-access-management'),
  ('Incident Response', 'incident-response'),
  ('ISO 27001', 'iso-27001'),
  ('JWT', 'jwt'),
  ('Malware Analysis', 'malware-analysis'),
  ('Network Security', 'network-security'),
  ('OAuth 2.0', 'oauth-2'),
  ('OpenID Connect', 'openid-connect'),
  ('OWASP', 'owasp'),
  ('Penetration Testing', 'penetration-testing'),
  ('PKI', 'pki'),
  ('Privacy Engineering', 'privacy-engineering'),
  ('SAST', 'sast'),
  ('Secure Coding', 'secure-coding'),
  ('Security Architecture', 'security-architecture'),
  ('Security Operations', 'security-operations'),
  ('SIEM', 'siem'),
  ('Software Composition Analysis', 'software-composition-analysis'),
  ('Threat Intelligence', 'threat-intelligence'),
  ('Threat Modeling', 'threat-modeling'),
  ('Vulnerability Management', 'vulnerability-management'),
  ('Zero Trust', 'zero-trust'),

  -- Quality assurance and testing (22)
  ('Accessibility Testing', 'accessibility-testing'),
  ('API Testing', 'api-testing'),
  ('Contract Testing', 'contract-testing'),
  ('Cypress', 'cypress'),
  ('End-to-End Testing', 'end-to-end-testing'),
  ('Exploratory Testing', 'exploratory-testing'),
  ('Integration Testing', 'integration-testing'),
  ('Jest', 'jest'),
  ('JUnit', 'junit'),
  ('k6', 'k6'),
  ('Load Testing', 'load-testing'),
  ('Mutation Testing', 'mutation-testing'),
  ('Performance Testing', 'performance-testing'),
  ('Playwright', 'playwright'),
  ('Postman', 'postman'),
  ('Property-Based Testing', 'property-based-testing'),
  ('pytest', 'pytest'),
  ('Quality Assurance', 'quality-assurance'),
  ('React Testing Library', 'react-testing-library'),
  ('Selenium', 'selenium'),
  ('Test Automation', 'test-automation'),
  ('Vitest', 'vitest'),

  -- Data and analytics (28)
  ('Apache Airflow', 'apache-airflow'),
  ('Apache Beam', 'apache-beam'),
  ('Apache Flink', 'apache-flink'),
  ('Apache Hadoop', 'apache-hadoop'),
  ('Apache Kafka', 'apache-kafka'),
  ('Apache Spark', 'apache-spark'),
  ('BigQuery', 'bigquery'),
  ('Business Intelligence', 'business-intelligence'),
  ('Data Analytics', 'data-analytics'),
  ('Data Engineering', 'data-engineering'),
  ('Data Governance', 'data-governance'),
  ('Data Lakes', 'data-lakes'),
  ('Data Modeling', 'data-modeling'),
  ('Data Warehousing', 'data-warehousing'),
  ('Databricks', 'databricks'),
  ('dbt', 'dbt'),
  ('ETL/ELT', 'etl-elt'),
  ('Jupyter', 'jupyter'),
  ('Looker', 'looker'),
  ('NumPy', 'numpy'),
  ('Pandas', 'pandas'),
  ('Power BI', 'power-bi'),
  ('Snowflake', 'snowflake'),
  ('Tableau', 'tableau'),
  ('Talend', 'talend'),
  ('Trino', 'trino'),
  ('Data Visualization', 'data-visualization'),
  ('Stream Processing', 'stream-processing'),

  -- Artificial intelligence and machine learning (32)
  ('AI Agents', 'ai-agents'),
  ('AI Ethics', 'ai-ethics'),
  ('Computer Vision', 'computer-vision'),
  ('Deep Learning', 'deep-learning'),
  ('Feature Engineering', 'feature-engineering'),
  ('Generative AI', 'generative-ai'),
  ('Hugging Face', 'hugging-face'),
  ('Keras', 'keras'),
  ('LangChain', 'langchain'),
  ('Large Language Models', 'large-language-models'),
  ('Machine Learning', 'machine-learning'),
  ('MLflow', 'mlflow'),
  ('MLOps', 'mlops'),
  ('Model Evaluation', 'model-evaluation'),
  ('Model Serving', 'model-serving'),
  ('Natural Language Processing', 'natural-language-processing'),
  ('ONNX', 'onnx'),
  ('OpenAI API', 'openai-api'),
  ('Prompt Engineering', 'prompt-engineering'),
  ('PyTorch', 'pytorch'),
  ('Recommender Systems', 'recommender-systems'),
  ('Reinforcement Learning', 'reinforcement-learning'),
  ('Responsible AI', 'responsible-ai'),
  ('Retrieval-Augmented Generation', 'retrieval-augmented-generation'),
  ('scikit-learn', 'scikit-learn'),
  ('TensorFlow', 'tensorflow'),
  ('Time Series Forecasting', 'time-series-forecasting'),
  ('Transformers', 'transformers'),
  ('Vertex AI', 'vertex-ai'),
  ('Vector Embeddings', 'vector-embeddings'),
  ('XGBoost', 'xgboost'),
  ('Amazon SageMaker', 'amazon-sagemaker'),

  -- Architecture and engineering practices (22)
  ('Clean Architecture', 'clean-architecture'),
  ('Clean Code', 'clean-code'),
  ('CQRS', 'cqrs'),
  ('Design Patterns', 'design-patterns'),
  ('Distributed Systems', 'distributed-systems'),
  ('Domain-Driven Design', 'domain-driven-design'),
  ('Enterprise Architecture', 'enterprise-architecture'),
  ('Event-Driven Architecture', 'event-driven-architecture'),
  ('Hexagonal Architecture', 'hexagonal-architecture'),
  ('High-Performance Computing', 'high-performance-computing'),
  ('Message-Driven Architecture', 'message-driven-architecture'),
  ('Object-Oriented Design', 'object-oriented-design'),
  ('Reactive Architecture', 'reactive-architecture'),
  ('Refactoring', 'refactoring'),
  ('Scalability', 'scalability'),
  ('Service-Oriented Architecture', 'service-oriented-architecture'),
  ('Software Architecture', 'software-architecture'),
  ('Software Design', 'software-design'),
  ('SOLID Principles', 'solid-principles'),
  ('Systems Design', 'systems-design'),
  ('Technical Debt Management', 'technical-debt-management'),
  ('Event Sourcing', 'event-sourcing'),

  -- Observability and operations (18)
  ('Application Performance Monitoring', 'application-performance-monitoring'),
  ('Datadog', 'datadog'),
  ('Distributed Tracing', 'distributed-tracing'),
  ('Dynatrace', 'dynatrace'),
  ('Elastic Stack', 'elastic-stack'),
  ('Error Tracking', 'error-tracking'),
  ('Grafana', 'grafana'),
  ('Incident Management', 'incident-management'),
  ('Jaeger', 'jaeger'),
  ('Log Management', 'log-management'),
  ('New Relic', 'new-relic'),
  ('OpenTelemetry', 'opentelemetry'),
  ('PagerDuty', 'pagerduty'),
  ('Prometheus', 'prometheus'),
  ('Service Level Objectives', 'service-level-objectives'),
  ('Splunk', 'splunk'),
  ('Synthetic Monitoring', 'synthetic-monitoring'),
  ('Uptime Monitoring', 'uptime-monitoring'),

  -- Systems and networking (22)
  ('Active Directory', 'active-directory'),
  ('Cisco IOS', 'cisco-ios'),
  ('Computer Networking', 'computer-networking'),
  ('DNS', 'dns'),
  ('Embedded Systems', 'embedded-systems'),
  ('FreeBSD', 'freebsd'),
  ('HTTP', 'http'),
  ('Internet of Things', 'internet-of-things'),
  ('Linux', 'linux'),
  ('Load Balancing', 'load-balancing'),
  ('macOS Administration', 'macos-administration'),
  ('Nginx', 'nginx'),
  ('Network Architecture', 'network-architecture'),
  ('Network Automation', 'network-automation'),
  ('OpenWrt', 'openwrt'),
  ('Real-Time Systems', 'real-time-systems'),
  ('TCP/IP', 'tcp-ip'),
  ('Unix', 'unix'),
  ('Virtualization', 'virtualization'),
  ('VPN', 'vpn'),
  ('Windows Server', 'windows-server'),
  ('Wireless Networking', 'wireless-networking'),

  -- Blockchain and Web3 (14)
  ('Bitcoin', 'bitcoin'),
  ('Blockchain', 'blockchain'),
  ('Consensus Algorithms', 'consensus-algorithms'),
  ('Cosmos SDK', 'cosmos-sdk'),
  ('Cryptocurrency', 'cryptocurrency'),
  ('Decentralized Applications', 'decentralized-applications'),
  ('Ethereum', 'ethereum'),
  ('Hyperledger Fabric', 'hyperledger-fabric'),
  ('IPFS', 'ipfs'),
  ('Rust Smart Contracts', 'rust-smart-contracts'),
  ('Smart Contracts', 'smart-contracts'),
  ('Solana', 'solana'),
  ('Solidity', 'solidity'),
  ('Web3', 'web3'),

  -- Game development, AR, and VR (14)
  ('3D Modeling', '3d-modeling'),
  ('ARCore', 'arcore'),
  ('ARKit', 'arkit'),
  ('Augmented Reality', 'augmented-reality'),
  ('Blender', 'blender'),
  ('CryEngine', 'cryengine'),
  ('Game Design', 'game-design'),
  ('Game Development', 'game-development'),
  ('Godot', 'godot'),
  ('Graphics Programming', 'graphics-programming'),
  ('OpenGL', 'opengl'),
  ('Unity', 'unity'),
  ('Unreal Engine', 'unreal-engine'),
  ('Virtual Reality', 'virtual-reality'),

  -- Design and product (20)
  ('Accessibility and Inclusion', 'accessibility-inclusion'),
  ('Adobe Creative Cloud', 'adobe-creative-cloud'),
  ('Content Design', 'content-design'),
  ('Customer Experience', 'customer-experience'),
  ('Design Systems', 'design-systems'),
  ('Figma', 'figma'),
  ('Graphic Design', 'graphic-design'),
  ('Human-Computer Interaction', 'human-computer-interaction'),
  ('Information Architecture', 'information-architecture'),
  ('Interaction Design', 'interaction-design'),
  ('Product Analytics', 'product-analytics'),
  ('Product Discovery', 'product-discovery'),
  ('Product Management', 'product-management'),
  ('Prototyping', 'prototyping'),
  ('Service Design', 'service-design'),
  ('UI Design', 'ui-design'),
  ('Usability Testing', 'usability-testing'),
  ('User Experience Design', 'user-experience-design'),
  ('User Research', 'user-research'),
  ('Wireframing', 'wireframing'),

  -- Agile and project delivery (20)
  ('Agile Coaching', 'agile-coaching'),
  ('Agile Delivery', 'agile-delivery'),
  ('Business Analysis', 'business-analysis'),
  ('Change Management', 'change-management'),
  ('Design Thinking', 'design-thinking'),
  ('Developer Experience', 'developer-experience'),
  ('Extreme Programming', 'extreme-programming'),
  ('IT Service Management', 'it-service-management'),
  ('ITIL', 'itil'),
  ('Kanban', 'kanban'),
  ('Lean Software Development', 'lean-software-development'),
  ('OKRs', 'okrs'),
  ('Portfolio Management', 'portfolio-management'),
  ('PRINCE2', 'prince2'),
  ('Product Roadmapping', 'product-roadmapping'),
  ('Project Management', 'project-management'),
  ('Requirements Engineering', 'requirements-engineering'),
  ('Risk Management', 'risk-management'),
  ('Scrum', 'scrum'),
  ('Stakeholder Management', 'stakeholder-management');
